<?php if (($_products = $block->getLoadedProductCollection()) && $_products->getSize()): ?>
    <ol class="product-items<?= ($block->getMode() === 'list') ? '' : ' product-items-images' ?>">
        <?php foreach ($_products->getItems() as $_product): ?>
            <li class="product-item">

            <?php if ($block->getMode() === 'list') : ?>
                <div class="product-item-info">
            <?php endif; ?>

                <a class="product-item-photo" href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                    title="<?= $block->escapeHtmlAttr($block->stripTags($_product->getName(), null, true)) ?>"
                    ><?= $block->getImage($_product, 'side_column_widget_product_thumbnail')->toHtml(); ?></a>

                <?php if ($block->getMode() === 'list') : ?>
                    <div class="product-item-details">
                        <strong class="product-item-name">
                            <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                title="<?= $block->escapeHtmlAttr($block->stripTags($_product->getName(), null, true)) ?>"
                                class="product-item-link"
                                ><?= $block->escapeHtml($this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name')) ?></a>
                        </strong>
                        <?= $block->getProductPriceHtml($_product, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE) ?>
                        <?= $block->getReviewsSummaryHtml($_product, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW) ?>
                    </div>
                <?php endif; ?>

            <?php if ($block->getMode() === 'list') : ?>
                    <div class="abs-add-clearfix"></div>
                </div>
            <?php endif; ?>

            </li>
        <?php endforeach; ?>
    </ol>
<?php endif; ?>
