<?php if (($_products = $block->getLoadedProductCollection()) && $_products->getSize()): ?>
    <?php $iterator = 1; ?>
    <ol class="product-items<?php echo ($this->getMode() === 'list') ? '' : ' product-items-images' ?>">
        <?php foreach ($_products->getItems() as $_product): ?>
            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>

            <?php if ($this->getMode() === 'list') : ?>
                <div class="product-item-info">
            <?php endif; ?>

                <a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"
                    title="<?php /* @escapeNotVerified */ echo $block->stripTags($_product->getName(), null, true) ?>"
                    ><?php echo $block->getImage($_product, 'side_column_widget_product_thumbnail')->toHtml(); ?></a>

                <?php if ($this->getMode() === 'list') : ?>
                    <div class="product-item-details">
                        <strong class="product-item-name">
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"
                                title="<?php /* @escapeNotVerified */ echo $block->stripTags($_product->getName(), null, true) ?>)"
                                class="product-item-link"
                                ><?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?></a>
                        </strong>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getReviewsSummaryHtml($_product, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW) ?>
                    </div>
                <?php endif; ?>

            <?php if ($this->getMode() === 'list') : ?>
                </div>
            <?php endif; ?>

            <?php echo($iterator == count($_products->getItems())+1) ? '</li>' : '' ?>
        <?php endforeach; ?>
    </ol>
<?php endif; ?>
