<?php if ($block->getEnabled()) : ?>
    <div class="block <?= $block->escapeHtml($block->getBlockCss()); ?>" style="display: none;" data-mage-init='{"Vovayatsyuk_Alsoviewed/js/list": <?= $block->escapeHtmlAttr($block->getJsonConfig()) ?>}'>
        <?php if ($block->getBlockTitle()) : ?>
            <div class="block-title"><strong><?= $block->escapeHtml($block->getBlockTitle()); ?></strong></div>
        <?php endif; ?>
        <div class="block-content"></div>
    </div>
<?php endif ?>
