<?php if ($this->getEnabled() && $this->getChildBlock('products')->getLoadedProductCollection()->count()) : ?>
    <div class="block <?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>">
        <div class="block-title"><strong><?php /* @escapeNotVerified */ echo $block->getBlockTitle(); ?></strong></div>
        <div class="block-content">
            <?php echo $block->getChildHtml(); ?>
        </div>
    </div>
<?php endif ?>
